[package]
name = "unity-version"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = { version = "0.99.17", default-features = false, features = ["deref", "deref_mut", "as_ref", "as_mut", "display"] }
nom = "7.1.3"
semver = "1.0.22"
serde = { version = "1.0.197", features = ["derive"] }
thiserror = "1.0.57"

[dev-dependencies]
proptest = "1.4.0"
quickcheck = "1.0.3"
